In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
data = {
    'students': ['navneet','rohit'],
    'subject': ['python', 'html'],
    'marks':[89,90]
}

In [4]:
data2 = {
    'students' : ['human','unknown'],
    'subject': ['dont know','life and death'],
    'marks': [99, 100]
}

In [6]:
df1 = pd.DataFrame(data)

In [7]:
df2 = pd.DataFrame(data2)

In [8]:
pd.concat([df1,df2])

  students         subject  marks
0  navneet          python     89
1    rohit            html     90
0    human       dont know     99
1  unknown  life and death    100

In [7]:
data3 = pd.DataFrame({
    'students': ['navneet','rohit','aryan', 'Unknown'],
    'subject': ['python', 'html', 'ML', 'AI'],
    'marks':[89,90, 100, 100]
}) 

data4 = pd.DataFrame({
    'Roll': [101,102,103,104],
    'Ranks': [99,100,1,1]
})

result = data3.join(data4)

In [8]:
print(result)

  students subject  marks  Roll  Ranks
0  navneet  python     89   101     99
1    rohit    html     90   102    100
2    aryan      ML    100   103      1
3  Unknown      AI    100   104      1

In [10]:
result.loc[0,["students","subject","Roll"]]

students    navneet
subject      python
Roll            101
Name: 0, dtype: object

In [15]:
result.iloc[[1,3],4]

1    100
3      1
Name: Ranks, dtype: int64

In [16]:
humans = {
    'students' :['Aryan',"unknow"],
    'subjects' : ['python','ml'],
    'marks' : [100,100]
}

beings = {
    'humanity' : ['human','human'],
    "empathy" : ["yes", "yes"]
}

In [17]:
humans = pd.DataFrame(humans)
beings = pd.DataFrame(beings)

In [18]:
pd.concat([humans,beings], ignore_index=True)

  students subjects  marks humanity empathy
0    Aryan   python  100.0      NaN     NaN
1   unknow       ml  100.0      NaN     NaN
2      NaN      NaN    NaN    human     yes
3      NaN      NaN    NaN    human     yes

In [19]:
data1 = {
    'students' : ['Aryan', 'Unknow'],
    'subjects' : ['python', 'Python'],
    'marks' : [100, 100]
}

data2 = {
    "students" : ['human', "being"],
    'subjects' : ['empathy', 'humanity'],
    'marks': [100, 100]
}

In [21]:
d1 = pd.DataFrame(data1)
d2 = pd.DataFrame(data2)

In [22]:
pd.concat([d1,d2], ignore_index=True)

  students  subjects  marks
0    Aryan    python    100
1   Unknow    Python    100
2    human   empathy    100
3    being  humanity    100

In [ ]:
# Series

In [30]:
data = pd.Series(['Bulvasaur','Ivysaur','Venusaur','Charmander','Charmelion','Charlizard'])

In [31]:
data

0     Bulvasaur
1       Ivysaur
2      Venusaur
3    Charmander
4    Charmelion
5    Charlizard
dtype: str

In [32]:
pokemons = { 1: "Bulvasaur",2:"Ivysaur",3:"Venusaur",4:"Charmander",5:"Charmelion",6:"Charlizard"}

In [33]:
print(pd.Series(pokemons))

1     Bulvasaur
2       Ivysaur
3      Venusaur
4    Charmander
5    Charmelion
6    Charlizard
dtype: str

In [24]:
# Masking

att = np.array([100,74,79,75,34,27,89])

att

array([100,  74,  79,  75,  34,  27,  89])

In [25]:
mask = att>74

mask

array([ True, False,  True,  True, False, False,  True])

In [26]:
data1 ={
    'Students':["aryan",'unknown','arun','april'],
    'Subjects':['python','html','java','rust'],
    'marks':[100,99,98,99]
}

df = pd.DataFrame(data1)
df

  Students Subjects  marks
0    aryan   python    100
1  unknown     html     99
2     arun     java     98
3    april     rust     99

In [30]:
df.insert(1,'Roll',[1,2,3,4])
df

  Students  Roll Subjects  marks
0    aryan     1   python    100
1  unknown     2     html     99
2     arun     3     java     98
3    april     4     rust     99

In [28]:
df.assign(City=['Kanpur','Delhi','Pune','Blr'])

  Students Subjects  marks    City
0    aryan   python    100  Kanpur
1  unknown     html     99   Delhi
2     arun     java     98    Pune
3    april     rust     99     Blr

In [31]:
df.drop('Roll',axis=1,inplace=True)
df

  Students Subjects  marks
0    aryan   python    100
1  unknown     html     99
2     arun     java     98
3    april     rust     99

In [33]:
df.drop(0,axis=0)

  Students Subjects  marks
1  unknown     html     99
2     arun     java     98
3    april     rust     99

In [34]:
for r in df.iterrows():
    print(r)

(0, Students     aryan
Subjects    python
marks          100
Name: 0, dtype: object)
(1, Students    unknown
Subjects       html
marks            99
Name: 1, dtype: object)
(2, Students    arun
Subjects    java
marks         98
Name: 2, dtype: object)
(3, Students    april
Subjects     rust
marks          99
Name: 3, dtype: object)

In [35]:
for r in df.itertuples():
    print(r)

Pandas(Index=0, Students='aryan', Subjects='python', marks=100)
Pandas(Index=1, Students='unknown', Subjects='html', marks=99)
Pandas(Index=2, Students='arun', Subjects='java', marks=98)
Pandas(Index=3, Students='april', Subjects='rust', marks=99)

In [36]:
df.sort_values(by='marks')

  Students Subjects  marks
2     arun     java     98
1  unknown     html     99
3    april     rust     99
0    aryan   python    100

In [37]:
df.sort_values(by='marks', ascending=False)

  Students Subjects  marks
0    aryan   python    100
1  unknown     html     99
3    april     rust     99
2     arun     java     98

In [40]:
df.duplicated()
df.duplicated(subset=['Students'])

0    False
1    False
2    False
3    False
dtype: bool

In [41]:
df.drop_duplicates()

  Students Subjects  marks
0    aryan   python    100
1  unknown     html     99
2     arun     java     98
3    april     rust     99